version: "3"
services:
  notebook:
    build: .
    ports: 
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes


# Comando para executar direto pela terminal
# docker run --rm -p 8888:8888 -e JUPYTER_ENABLE_LAB=yes -v "${PWD}":/home/jovyan/work jupyter/minimal-notebook:33add21fab64